name: Releases

on: 
  push:
    branches:
    - main
  release:
    types: [released]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set file
      id: filesetting
      run: echo "::set-output name=metrics_report::fga-eps-mds-${{github.event.repository.name}}-$(date "+%m-%d-%Y-%H-%M")"
   
    - name: Get metrics
      id: metrics
      run: curl "${{secrets.SONAR_URL}}" > ${{steps.filesetting.outputs.metrics_report}}.json
      
    - name: Get release version
      id: new_tag
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set artifact
      uses: ncipollo/release-action@v1.8.9
      with:
        tag: ${{steps.new_tag.outputs.new_tag}}
        artifacts: ${{steps.filesetting.outputs.metrics_report}}.json
        body: ${{steps.new_tag.outputs.changelog}}
        token: ${{ secrets.GITHUB_TOKEN }}
  
  send-release:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: Frontend
    steps:
      - uses: guilouro/multiple-repositories-dispatch@v1.0.0
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          event_type: event_name
          repositories: |
            fga-eps-mds/2021-1-PUMA
          client_payload: '{"repo_name": "${{ env.REPO_NAME }}"}'
