name: Dispatch event
on:
  release:
    types: [released]
jobs:
  send-release:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: Frontend
    steps:
      - uses: guilouro/multiple-repositories-dispatch@v1.0.0
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          event_type: event_name
          repositories: |
            fga-eps-mds/2021-1-PUMA
          client_payload: '{"repo_name": "${{ env.REPO_NAME }}"}'
